### ISSUE TITLE
Since the 1.5.1 update SickRage doesn't start

### ISSUE THREAD

**Issue by bikehead** [lsellens/service.downloadmanager.SickPotatoHead#3]
Couch and Headphone start, but SickRage fails.  The last error I saw in my logs was for some files in gui/slick/menus (I think) but there is no such directory in the 1.5.1 zip files.  I uninstalled and reinstalled the latest SickPotato but still no start.   I'd love to include a log, but no log for SickRage is created and I can't find any mention of SickRage in the kodi.log.

**Comment by bikehead** [comment]
It was the gui/sick/interfaces directory which is in 1.5.0 but not in 1.5.1.

**Comment by bikehead** [comment]
Ok,  I was tried to start SickRage myself using the same launch command as Kodi tries and I got the following python error:
OpenELEC:~ # python /storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/SickBeard.py --daemon --datadir /storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotat
oHead/ --pidfile=/var/run/sickbeard.pid --config /storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sickbeard.ini
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/SickBeard.py", line 53, in <module>
    import sickbeard
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/**init**.py", line 37, in <module>
    from sickbeard import metadata
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/metadata/**init**.py", line 22, in <module>
    import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/metadata/kodi.py", line 19, in <module>
    import generic
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/metadata/generic.py", line 29, in <module>
    from sickbeard import helpers
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/helpers.py", line 74, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/subtitles.py", line 26, in <module>
    import subliminal
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/subliminal/**init**.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles, save_subtitles
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/subliminal/api.py", line 8, in <module>
    import babelfish
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/babelfish/**init**.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/babelfish/converters/**init**.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 698, in <module>
    class Environment(object):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 701, in Environment
    def **init**(self, search_path=None, platform=get_supported_platform(), python=PY_MAJOR):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 96, in get_supported_platform
    plat = get_build_platform(); m = macosVersionString.match(plat)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 221, in get_build_platform
    from distutils.util import get_platform
ImportError: No module named distutils.util

**Comment by leoaf79** [comment]
Same here. Using RBPI 2 Openlec.

**Comment by Zkiwi** [comment]
See info here https://github.com/lsellens/service.downloadmanager.SickPotatoHead/issues/2 for a link to an OpenElec forum message with a recommended fix.
Unfortunately for me the recommended fix has not worked but for most people it seems to be working. I'm not sure if I am doing something wrong or my setup is different in some way.

**Comment by Zkiwi** [comment]
After following the instructions exactly as shown in the link above i know have SickRage WebUI loaded and working. Be careful to follow instructions exactly. Make sure no tabs in the amended file. I used notepad ++ to edit and had to delete the tab space after the line return and replace with spaces to make it work correctly.

**Comment by leoaf79** [comment]
This worked for me:
http://openelec.tv/forum/110-update-openelec/74763-nzbtomedia-postprocessing-missing-distils-util#132250

**Comment by lsellens** [comment]
update to 1.5.3 this should be fixed
